name: Maven CI/CD

on:
 push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
 build:
    runs-on: ubuntu-20.04
    needs: compile
    name: Build the Maven Project
    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v2
      with:
        path: ~/.m2/spring-social
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    - name: Set up JDK 12
      uses: actions/setup-java@v2
      with:
          distribution: 'adopt'
          java-version: '12'
          java-package: jdk
    - name: Build and test project
      working-directory: github-actions-java-maven
      run: mvn -B verify
    - name: Upload Maven build artifact
      uses: actions/upload-artifact@v2
      with:
        name: artifact.jar
        path: github-actions-java-maven/target/github-actions-java-maven.jar
